/**
 * Per-file complexity ratchet: counts of complexity/max-params/max-statements findings may fall, never rise.
 *
 * Why this exists on top of eslint's own overrides: a per-file override or an
 * `eslint-disable` comment silences a rule for the WHOLE file, so once a file is
 * baselined a brand-new complexity-15 function in it passes untouched. This
 * script runs eslint with an isolated config (`eslint.ratchet.config.js`) and
 * `--no-inline-config`, counts findings per (file, rule), and compares against
 * `complexity-baseline.json`.
 *
 * A count ABOVE its baseline fails (growth). A count BELOW its baseline also
 * fails: silent headroom to regress into with CI green. Lock the improvement in
 * with `--update` in the same change that earned it.
 *
 * Usage:
 *
 *     tsx scripts/check-complexity-ratchet.ts            # enforce
 *     tsx scripts/check-complexity-ratchet.ts --update   # rewrite the baseline
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { displayPath, isMain, REPO, report } from './_check-runner.js';

export const BASELINE = path.join(REPO, 'complexity-baseline.json');
export const RULES = ['complexity', 'max-params', 'max-statements'] as const;
const SCAN_DIRS = ['app', 'scripts'];
const COMMENT =
  'Complexity ratchet baseline: counts of complexity/max-params/max-statements findings per file, generated by ' +
  'scripts/check-complexity-ratchet.ts --update. Counts may only fall: CI fails if any count rises or a new file ' +
  'appears, and a stale (too-high) entry also fails so improvements get locked in.';

export type Counts = Record<string, Record<string, number>>;

interface EslintMessage {
  ruleId: string | null;
}
interface EslintResult {
  filePath: string;
  messages: EslintMessage[];
}

/** Current findings per (file, rule) with the isolated eslint config. */
export function measure(): Counts {
  const eslint = path.join(REPO, 'node_modules', 'eslint', 'bin', 'eslint.js');
  const result = spawnSync(
    process.execPath,
    [
      eslint,
      '--config',
      'eslint.ratchet.config.js',
      '--no-inline-config',
      '--format',
      'json',
      '--no-error-on-unmatched-pattern',
      ...SCAN_DIRS,
    ],
    { cwd: REPO, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );
  if (result.status !== 0 && result.status !== 1) {
    throw new Error(`eslint failed: ${result.stderr.trim()}`);
  }
  const counts: Counts = {};
  for (const file of JSON.parse(result.stdout === '' ? '[]' : result.stdout) as EslintResult[]) {
    for (const message of file.messages) {
      if (message.ruleId === null || !(RULES as readonly string[]).includes(message.ruleId)) {
        continue;
      }
      const rel = displayPath(file.filePath);
      const perFile = (counts[rel] ??= {});
      perFile[message.ruleId] = (perFile[message.ruleId] ?? 0) + 1;
    }
  }
  return sorted(counts);
}

function sorted(counts: Counts): Counts {
  const out: Counts = {};
  for (const file of Object.keys(counts).sort()) {
    const rules = counts[file] ?? {};
    out[file] = Object.fromEntries(
      Object.keys(rules)
        .sort()
        .map((r) => [r, rules[r] ?? 0]),
    );
  }
  return out;
}

/** Baseline counts from disk (empty if absent). */
export function loadBaseline(file: string = BASELINE): Counts {
  if (!existsSync(file)) {
    return {};
  }
  const data = JSON.parse(readFileSync(file, 'utf8')) as { counts?: Counts };
  return data.counts ?? {};
}

function rises(current: Counts, baseline: Counts): string[] {
  const out: string[] = [];
  for (const [file, rules] of Object.entries(current)) {
    for (const [rule, n] of Object.entries(rules)) {
      const allowed = baseline[file]?.[rule] ?? 0;
      if (n > allowed) {
        out.push(
          `${file}: ${rule} rose ${allowed} -> ${n}; simplify, or argue the increase and run --update`,
        );
      }
    }
  }
  return out;
}

function staleEntries(current: Counts, baseline: Counts): string[] {
  const out: string[] = [];
  for (const [file, rules] of Object.entries(baseline)) {
    for (const [rule, allowed] of Object.entries(rules)) {
      const n = current[file]?.[rule] ?? 0;
      if (n < allowed) {
        out.push(
          `${file}: ${rule} improved ${allowed} -> ${n}; lock it in with \`npm run lint.complexity.update\``,
        );
      }
    }
  }
  return out;
}

/** Violations: any rise, any new file, and any stale (too-high) baseline entry. */
export function compare(current: Counts, baseline: Counts): string[] {
  return [...rises(current, baseline), ...staleEntries(current, baseline)].sort();
}

/** Persist `counts` as the new baseline. */
export function writeBaseline(counts: Counts, file: string = BASELINE): void {
  writeFileSync(file, JSON.stringify({ _comment: COMMENT, counts }, null, 2) + '\n');
}

export function main(argv: readonly string[]): number {
  const current = measure();
  if (argv.includes('--update')) {
    writeBaseline(current);
    const total = Object.values(current).reduce(
      (sum, rules) => sum + Object.values(rules).reduce((a, b) => a + b, 0),
      0,
    );
    console.log(`complexity baseline written: ${total} findings`);
    return 0;
  }
  return report('Complexity ratchet', compare(current, loadBaseline()), {
    okMessage: 'complexity ratchet: OK',
  });
}

if (isMain(import.meta)) {
  process.exitCode = main(process.argv.slice(2));
}
